---
name: Auto-Merge

on: # yamllint disable-line rule:truthy
  pull_request_target:
    types: [opened, synchronize]

jobs:
  auto-merge:
    uses: HeadlessTarry/.github/.github/workflows/auto-merge.yml@8b85aabd86bb0b8e85f8f9d8fb682e9cdabf8beb
    permissions: {}
    secrets:
      AUTO_PRS_PRIVATE_KEY: ${{ secrets.AUTO_PRS_PRIVATE_KEY }}
