---
name: Auto-Merge

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  auto-merge:
    uses: HeadlessTarry/.github/.github/workflows/auto-merge.yml@3ada7956fe61e119460f693cc0c1324f357f501c
    permissions:
      pull-requests: write
      contents: write
