---
name: Auto-Merge

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  auto-merge:
    uses: HeadlessTarry/.github/.github/workflows/auto-merge.yml@fd4d97fb32215ed0182e95f597af954baa2881d1
    permissions:
      pull-requests: write
      contents: write
