---
name: Continuous Integration

# yamllint disable-line rule:truthy
on:
  push:
    branches: [main]
  pull_request:
  merge_group:

jobs:
  sonarqube:
    name: 🔍 SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: 📡 Run scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
